"""Tests for the generated DynSpire Python bindings (ctypes, codegen).

Run with:  uv run pytest tests/

Exercises the full typed API surface generated by dynspire-codegen's
``generate_python``: compress/decompress round-trip, integer encoding,
out-vec auto-tuple, Vec<String>/Vec<Vec<u8>> returns, opaque round-trip,
enum round-trip, Option<T>, lifecycle, and GIL release.
"""

import os
import sys

import pytest

# Add generated module to path
_GEN_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "demo",
    "rle-spier",
    "generated",
)
if _GEN_DIR not in sys.path:
    sys.path.insert(0, _GEN_DIR)

from rle import CompressionReport, DynSpireError, Rle, Tone  # noqa: E402

DATA = b"AAAABBBCCCCDDDDDEEEEFFFFFFGGG"
COMPRESSED = bytes.fromhex("0441034204430544044506460347")


def _find_lib():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for d in ("target/debug", "target/release"):
        path = os.path.join(root, d, "librle_spier.so")
        if os.path.exists(path):
            return path
    pytest.skip("rle_spier .so not built — run: cargo build")


@pytest.fixture
def lib_path():
    return _find_lib()


@pytest.fixture
def c(lib_path):
    with Rle(lib_path) as client:
        yield client


# ---------------------------------------------------------------------------
# Compress / decompress round-trip
# ---------------------------------------------------------------------------

class TestCompress:
    def test_compress(self, c):
        assert c.compress(DATA) == COMPRESSED

    def test_decompress(self, c):
        assert c.decompress(COMPRESSED) == DATA

    def test_round_trip(self, c):
        assert c.decompress(c.compress(DATA)) == DATA

    def test_compress_empty(self, c):
        assert c.compress(b"") == b""

    def test_decompress_empty(self, c):
        assert c.decompress(b"") == b""


# ---------------------------------------------------------------------------
# Integer encoding (regression: ints were encoded as float bit patterns)
# ---------------------------------------------------------------------------

class TestIntegerEncoding:
    def test_stats_returns_correct_integers(self, c):
        orig, comp = c.stats(DATA)
        assert orig == 29
        assert comp == 14

    def test_stats_types(self, c):
        orig, comp = c.stats(DATA)
        assert isinstance(orig, int)
        assert isinstance(comp, int)

    def test_first_byte_some(self, c):
        assert c.first_byte(DATA) == 65  # ord('A')

    def test_first_byte_none(self, c):
        assert c.first_byte(b"") is None


# ---------------------------------------------------------------------------
# Out-vec auto-tuple
# ---------------------------------------------------------------------------

class TestOutVec:
    def test_compress_into_returns_tuple(self, c):
        ret, outs = c.compress_into(DATA)
        assert ret is None
        assert len(outs) == 1
        assert outs[0] == COMPRESSED

    def test_compress_into_checked_returns_bool(self, c):
        ok, outs = c.compress_into_checked(DATA)
        assert ok is True
        assert outs[0] == COMPRESSED


# ---------------------------------------------------------------------------
# Vec<Vec<u8>> and Vec<String> returns
# ---------------------------------------------------------------------------

class TestReturnTypes:
    def test_split_runs(self, c):
        runs = c.split_runs(DATA)
        assert len(runs) == 7
        assert bytes(runs[0]) == b"AAAA"
        assert bytes(runs[-1]) == b"GGG"

    def test_run_labels(self, c):
        labels = c.run_labels(DATA)
        assert labels == ["4xA", "3xB", "4xC", "5xD", "4xE", "6xF", "3xG"]

    def test_split_runs_empty(self, c):
        assert c.split_runs(b"") == []

    def test_run_labels_empty(self, c):
        assert c.run_labels(b"") == []


# ---------------------------------------------------------------------------
# Opaque handle round-trip
# ---------------------------------------------------------------------------

class TestOpaqueHandle:
    def test_analyze_and_report(self, c):
        report = c.analyze(DATA)
        assert isinstance(report, CompressionReport)
        summary = c.report_summary(report)
        assert "original=29" in summary

    def test_repr_shows_type_name(self, c):
        report = c.analyze(DATA)
        assert "CompressionReport" in repr(report)


# ---------------------------------------------------------------------------
# Enum round-trip
# ---------------------------------------------------------------------------

class TestEnum:
    def test_classify_returns_loud(self, c):
        tone = c.classify(DATA)
        assert tone.variant == "Loud"

    def test_enum_equality(self, c):
        loud = c.classify(DATA)
        assert loud == Tone.Loud(71)  # 'G' = 71 is the loudest byte
        assert loud != Tone.Quiet()

    def test_describe_quiet(self, c):
        assert c.describe_tone(Tone.Quiet()) == "silence"

    def test_describe_loud(self, c):
        assert c.describe_tone(Tone.Loud(0)) == "loud(0)"

    def test_enum_repr(self):
        assert repr(Tone.Loud(42)) == "Tone.Loud(42)"
        assert repr(Tone.Quiet()) == "Tone.Quiet"


# ---------------------------------------------------------------------------
# Lifecycle
# ---------------------------------------------------------------------------

class TestLifecycle:
    def test_context_manager(self, lib_path):
        with Rle(lib_path) as c:
            assert c.compress(DATA) == COMPRESSED

    def test_create_with_config(self, lib_path):
        with Rle(lib_path, {"key": "value"}) as c:
            assert c.compress(DATA) == COMPRESSED

    def test_close_is_idempotent(self, lib_path):
        c = Rle(lib_path)
        c.close()
        c.close()  # should not raise

    def test_hash_mismatch_raises(self, lib_path):
        import rle
        original = rle.Rle._idl_hash_const
        try:
            rle.Rle._idl_hash_const = 0xDEAD
            with pytest.raises(DynSpireError, match="IDL hash mismatch"):
                Rle(lib_path)
        finally:
            rle.Rle._idl_hash_const = original


# ---------------------------------------------------------------------------
# GIL release during dispatch
# ---------------------------------------------------------------------------

class TestGilRelease:
    def test_gil_released_during_dispatch(self, lib_path):
        """ctypes CDLL releases the GIL during the C call. A background
        thread should be able to run while the spier sleeps."""
        import threading
        import time

        ran_at = [None]

        def background():
            ran_at[0] = time.perf_counter()

        start = time.perf_counter()
        t = threading.Thread(target=background, daemon=True)
        t.start()

        with Rle(lib_path) as c:
            c.delay(300)

        t.join(timeout=5)
        assert ran_at[0] is not None
        bg_delay_ms = (ran_at[0] - start) * 1000
        assert bg_delay_ms < 250, (
            f"Background thread ran {bg_delay_ms:.0f}ms after start — "
            f"GIL was not released during dispatch"
        )

    def test_delay_returns_none(self, c):
        assert c.delay(1) is None
