use std::collections::HashMap;
use std::ffi::c_void;
use std::path::PathBuf;
use std::sync::Arc;

use crate::kvmap::serialize_kvmap;
use crate::slots::MAX_OUT_SLOTS;

type FnIdlHash = unsafe extern "C" fn() -> u64;
type FnCreate = unsafe extern "C" fn(*const u8, usize) -> *mut c_void;
type FnDestroy = unsafe extern "C" fn(*mut c_void);
type FnDispatch = unsafe extern "C" fn(
    *mut c_void,
    *const u64,
    usize,
    *mut u64,
    usize,
) -> u8;

pub struct MethodConfig {
    pub name: &'static str,
}

/// Static IDL metadata generated by the DSL codegen (`build.rs` + `.dspi`).
///
/// Passed to [`DynSpireClient::connect`] for hash verification and method
/// resolution. Always use the generated `IDL` static from the IDL crate —
/// do not construct this manually.
///
/// ```ignore
/// let client = DynSpireClient::connect("my_spier", &my_idl::IDL, &config)?;
/// ```
pub struct IdlDescriptor {
    pub hash: u64,
    pub methods: &'static [&'static str],
}

/// Trait implemented by the `{Prefix}Op` enum generated by the DSL codegen.
///
/// Enables type-safe dispatch: each generated method calls
/// `client.dispatch(MyOp::DoThing as usize, ...)` — raw integers
/// are a compile-time error.
pub trait SpierOp {
    fn as_index(self) -> usize;
}

struct Handle(*mut c_void);
unsafe impl Send for Handle {}
unsafe impl Sync for Handle {}

fn load_sym<T: Copy>(lib: &libloading::Library, name: &[u8]) -> Result<T, String> {
    unsafe {
        let sym: libloading::Symbol<T> = lib
            .get(name)
            .map_err(|e| format!("symbol {}: {e}", String::from_utf8_lossy(name)))?;
        Ok(*sym)
    }
}

pub struct DynSpireLib {
    _lib: libloading::Library,
    dispatch: Arc<Vec<FnDispatch>>,
    create: FnCreate,
    destroy: FnDestroy,
}

unsafe impl Send for DynSpireLib {}
unsafe impl Sync for DynSpireLib {}

impl DynSpireLib {
    pub fn load(
        so_path: &str,
        idl_hash: u64,
        methods: &[MethodConfig],
    ) -> Result<Self, String> {
        let lib = unsafe {
            libloading::Library::new(so_path)
                .map_err(|e| format!("dlopen {}: {e}", so_path))?
        };

        let fn_hash: FnIdlHash = load_sym(&lib, b"dynspire_idl_hash\0")?;
        let hash = unsafe { fn_hash() };
        if hash != idl_hash {
            return Err(format!(
                "IDL hash mismatch: spier=0x{:016x}, expected=0x{:016x}",
                hash, idl_hash
            ));
        }

        let fn_create: FnCreate = load_sym(&lib, b"dynspire_create\0")?;
        let fn_destroy: FnDestroy = load_sym(&lib, b"dynspire_destroy\0")?;

        let mut dispatch = Vec::with_capacity(methods.len());
        for config in methods {
            let sym_name = format!("dynspire_dispatch_{}\0", config.name);
            let fn_ptr: FnDispatch = load_sym(&lib, sym_name.as_bytes())?;
            dispatch.push(fn_ptr);
        }

        Ok(Self {
            _lib: lib,
            dispatch: Arc::new(dispatch),
            create: fn_create,
            destroy: fn_destroy,
        })
    }

    pub fn create_client(
        self: &Arc<Self>,
        config: &HashMap<String, String>,
    ) -> Result<DynSpireClient, String> {
        let buf = serialize_kvmap(config);
        let handle_ptr = unsafe { (self.create)(buf.as_ptr(), buf.len()) };
        if handle_ptr.is_null() {
            return Err("spier create returned null".into());
        }
        Ok(DynSpireClient {
            lib: Arc::clone(self),
            handle: Arc::new(Handle(handle_ptr)),
        })
    }

    pub fn find(name: &str) -> Result<String, String> {
        let filename = format!("lib{name}.so");

        if let Ok(dir) = std::env::var("DYNSPIRE_LIB_DIR") {
            let path = PathBuf::from(&dir).join(&filename);
            if path.exists() {
                return Ok(path.to_string_lossy().into_owned());
            }
            return Err(format!(
                "spier not found: {} (DYNSPIRE_LIB_DIR={dir})",
                path.display()
            ));
        }

        Ok(filename)
    }
}

/// Runtime client for calling a loaded spier.
///
/// Created via [`DynSpireClient::connect`]. Calls methods through the slot
/// protocol — arguments are encoded as `u64` slots, dispatched via FFI,
/// and the response is decoded back to a typed Rust value.
///
/// `Clone` is cheap (inner state is `Arc`-shared). `Drop` calls
/// `dynspire_destroy` automatically when the last clone is dropped.
pub struct DynSpireClient {
    lib: Arc<DynSpireLib>,
    handle: Arc<Handle>,
}

unsafe impl Send for DynSpireClient {}
unsafe impl Sync for DynSpireClient {}

impl Clone for DynSpireClient {
    fn clone(&self) -> Self {
        Self {
            lib: Arc::clone(&self.lib),
            handle: Arc::clone(&self.handle),
        }
    }
}

impl DynSpireClient {
    /// Loads a spier `.so`, verifies its IDL hash, and creates a client instance.
    ///
    /// The `idl` parameter must be the `&'static IDL` generated by
    /// the `IDL` static generated by the DSL codegen in the IDL crate. The spier is found by name
    /// via `DYNSPIRE_LIB_DIR` or `LD_LIBRARY_PATH`.
    ///
    /// ```ignore
    /// let client = DynSpireClient::connect("my_spier", &my_idl::IDL, &config)?;
    /// ```
    pub fn connect(
        spier_name: &str,
        idl: &'static IdlDescriptor,
        config: &HashMap<String, String>,
    ) -> Result<Self, String> {
        let so_path = DynSpireLib::find(spier_name)?;
        let methods: Vec<MethodConfig> = idl
            .methods
            .iter()
            .map(|&n| MethodConfig { name: n })
            .collect();
        let lib = DynSpireLib::load(&so_path, idl.hash, &methods)?;
        Arc::new(lib).create_client(config)
    }

    pub fn load(
        so_path: &str,
        idl_hash: u64,
        methods: &[MethodConfig],
        config: &HashMap<String, String>,
    ) -> Result<Self, String> {
        let lib = DynSpireLib::load(so_path, idl_hash, methods)?;
        Arc::new(lib).create_client(config)
    }

    pub fn dispatch(
        &self,
        method: usize,
        in_slots: &[u64],
        out_slots: &mut [u64; MAX_OUT_SLOTS],
    ) -> Result<(), String> {
        let dispatch_fn = self
            .lib
            .dispatch
            .get(method)
            .ok_or_else(|| format!("unknown dispatch index: {method}"))?;

        let ret = unsafe {
            dispatch_fn(
                self.handle.0,
                in_slots.as_ptr(),
                in_slots.len(),
                out_slots.as_mut_ptr(),
                MAX_OUT_SLOTS,
            )
        };
        if ret != 0 {
            return Err(format!("dispatch transport error (code {ret})"));
        }
        Ok(())
    }
}

impl Drop for DynSpireClient {
    fn drop(&mut self) {
        if Arc::strong_count(&self.handle) == 1 {
            unsafe {
                (self.lib.destroy)(self.handle.0);
            }
        }
    }
}
